name: poutine - GitHub Actions SAST
description: |
  BoostSecurity.io’s poutine detects vulnerabilities and misconfigurations in your GitHub Actions workflows.
branding:
  icon: align-center
  color: yellow
inputs:
  format:
    description: 'Report format'
    default: sarif
    required: true
  output:
    description: 'Report file output'
    default: results.sarif
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        poutine analyze_local "$GITHUB_WORKSPACE" --format "$INPUT_FORMAT" > "$INPUT_OUTPUT"
